### ISSUE TITLE
Script not adding WILDCARD_ZONE domain to hosts file

### ISSUE THREAD

**Issue by umefarooq** [virtualhost/virtualhost.sh#76] opened 2016-03-03 19:16 UTC
Hi
i have enable WILDCARD_ZONE in config file, it is showing Create http://virtualhost.dev:80/? [Y/n]: but is not adding to domain you can access domain http://virtualhost not like virtualhost.dev

**Comment by star-szr** [comment] 2016-03-07 00:29
I'm not overly familiar with this piece of functionality but looking at the code I can't see any reason why this shouldn't work if you have WILDCARD_ZONE set to "dev". Keep in mind that all virtualhost.sh is doing is adding a ServerAlias to your VirtualHost:

https://github.com/virtualhost/virtualhost.sh/blob/master/virtualhost.sh#L153

So as long as virtualhost.sh is adding the ServerAlias including the WILDCARD_ZONE to the VirtualHost files it's creating, it's doing its job and the problem is elsewhere.

If that doesn't solve your problem can you paste the contents of your config file and also provide more information about what you're experiencing?

**Comment by umefarooq** [comment] 2016-03-09 04:41
yes its adding, but in host file its not adding wildcard, host file has 
127.0.0.1 virtualhost
if wild card is available than host file should have both
127.0.0.1 virtualhost
127.0.0.1 virtualhost.dev

so in browser we can access virtualhost with or without wildcard.

**Comment by star-szr** [comment] 2016-03-09 12:24
I think you might be misunderstanding this feature. The intent of this feature is not to add more items to your hosts file for you automatically. Instead you would either set up something outside your network like [DynDNS](http://dyn.com) or set up something like [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html) on your machine to resolve all `*.dev` hosts to 127.0.0.1. Or set up a DNS server in your network to do this. This is where the wildcard part comes in, with the `wildcard_string` you set, `*.wildcard_string` should resolve to your machine. That is outside of what virtualhost.sh is doing, all virtualhost.sh is doing if this is specified is adding the ServerAlias to the wildcard VirtualHost to ensure the right VirtualHost is served by Apache when the wildcard version of the host is used.

From the script:

```
# If defined, a ServerAlias os $1.$WILDCARD_ZONE will be added to the virtual
# host file. This is useful if you, for example, have set up a wildcard domain
# either on your own DNS server or using a server like dyndns.org. For example,
# if my local IP of 10.0.42.42 is static (which can still be achieved using a
# well-configured DHCP server or an Apple Airport Extreme 802.11n base station)
# and I create a host on dyndns.org of patrickdev.dyndns.org with wildcard
# hostnames turned on, then defining my WILDCARD_ZONE to "patrickdev.dyndns.org"
# will enable access to my virtual host from any machine on the network. Note
# that this would also work with a public IP too, and the virtual hosts on your
# machine would be accessible to anyone on the internets.
```

If you have suggestions for making the documentation here clearer please let me know. The use case presented here doesn't seem like a common one so I'm not sure this specific feature should be added. I'm going to close this issue because virtualhost.sh works as designed here, feel free to leave further comments though. Thanks.

**Closed as completed by star-szr** 2016-03-09 12:24 UTC
